---
output:
  pdf_document: default
  html_document: default
---

# PROJECT PROPOSAL RESPONSE

## (1) Project title
Diabetes Risk Group

## (2) Names of everyone in the group:
Henry Tan ht492; Casper Liao cl2622

## (3) One sentence describing the dataset and url link to the dataset (e.g. webscraped data of Ithaca restaurants on Yelp, or county-level income data downloaded from the US census bureau website, etc)

+ One sentence: The Diabetes Health Indicators Dataset contains healthcare statistics and lifestyle survey information about people in general along with their diagnosis of diabetes.

# TODO!
+ Link: https://www.cdc.gov/brfss/annual_data/annual_2014.html
+ Link2: https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators

https://www.kaggle.com/datasets/adilshamim8/social-media-addiction-vs-relationships


## (4) One or two questions about the dataset you will answer in the project, preferably one.

Question: What kind of group of people (combination of other health characteristics) has a higher chance of getting diabetes?

## (5) The head of the dataset (first 6 lines). 

```{r, echo=FALSE}
df <- read.csv("Students Social Media Addiction.csv")
head(df)
```




